services:
  postgres:
    image: postgres:16-alpine
    container_name: inventory-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: inventory_admin_2024
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .\docker\init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  postgres_data:
    name: inventory_postgres_data