"""Add user tracking, notes, and applications

Revision ID: 9f0364715da0
Revises: 81d9590ea559
Create Date: 2025-08-16 18:04:02.467885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0364715da0'
down_revision: Union[str, None] = '81d9590ea559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('primary_owner_id', sa.UUID(), nullable=True))
    op.add_column('assets', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_assets_primary_owner_id'), 'assets', ['primary_owner_id'], unique=False)
    op.create_foreign_key(None, 'assets', 'users', ['primary_owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_index(op.f('ix_assets_primary_owner_id'), table_name='assets')
    op.drop_column('assets', 'notes')
    op.drop_column('assets', 'primary_owner_id')
    # ### end Alembic commands ###
